name: fmi-cross-checks

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test-cross-check-script ]
  pull_request:
    branches: [ test-cross-check-script ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest
    strategy:
      # Don't cancel in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        julia-version: ['1.6', 'nightly']
        julia-arch: [x64]
    steps:
      - uses: actions/checkout@v2

      # Set up Julia
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}


     # Build  package
      - name: "run check script"
        run: |
            julia -e  '
            using Pkg
            Pkg.add(\"FMI\")
            Pkg.add(\"CSV\")
            Pkg.add(\"DataFrames\")
            Pkg.add(\"StatsPlots\")
            Pkg.add(\"Plots\")'
            julia crosscheckscript.jl
            
    # Commit and push changes
      - name: "commit and push changes"
        run: |
          git config --global user.name 'JoKircher'
          git config --global user.email 'JoKircher@users.noreply.github.com'
          git add *
          git commit -m "results of FMI.jl simulations"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ test-cross-check-script }}
